
import './globals.css';
import { Providers } from './providers';
import StyledJsxRegistry from './registry';
import Header from '@/src/Components/Header';
import Footer from '@/src/Components/Footer';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="gs" >
      {/* className={inter.className} */}
      <body >
        <Providers>
          <StyledJsxRegistry>
          <Header />
            {children}
          <Footer />
            </StyledJsxRegistry>
        </Providers>
      </body>
    </html>
  );
}
